### ISSUE TITLE
Add redirects for old URLs

### ISSUE THREAD

**Issue by nielsrowinbik** [nielsrowinbik/mac-select#17]
URL's used to contain a unique ID, this is no longer the case. These lines should be added to `netlify.toml`.

```toml
[[redirects]]
  from = "/aanbod/:id/:slug"
  to = "/aanbod/:slug"
  status = 301
  force = false
[[redirects]]
  from = "/blog/:date/:month/:year/:id/:slug"
  to = "/blog/:slug"
  status = 301
  force = false
[[redirects]]
  from = "/verkopen"
  to = "/hulp#verkoop"
  status = 301
  force = false
```
